apiVersion: postgresql.sql.${APIGROUP_SUFFIX}crossplane.io/v1alpha1
kind: Grant
metadata:
  name: issue-240-grant
spec:
  forProvider:
    database: my-service
    privileges:
      - CONNECT
    revokePublicOnDb: true
    role: my-service_user
  managementPolicies:
    - '*'
  providerConfigRef:
    ${PROVIDERCONFIG_KIND_LINE}
    name: default
